version: "3.6"

networks:
  previewer:

services:
  image-previewer:
    container_name: image-previewer
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080"
    environment:
      - CACHE_CAPACITY=${CACHE_CAPACITY}
    networks:
      - previewer

  nginx:
    image: nginx:1.21.4
    ports:
      - "80:80"
    volumes:
      - ./build/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - image-previewer
    depends_on:
      - image-previewer
    networks:
      - previewer
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost" ]
      interval: 1m30s
      timeout: 2s
      retries: 3
      start_period: 40s